/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package framesmarianna_maria;

import ADM.acesso;
import ADM.funcionario;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author silva
 */
public class inicio extends javax.swing.JFrame {
    acesso c = new acesso();
    SimpleDateFormat form = new SimpleDateFormat("dd/MM/yyyy");
    String Adm = null;
    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
         jPanel2.setVisible(false);
        jPanel1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        Da = new javax.swing.JFormattedTextField();
        VH = new javax.swing.JFormattedTextField();
        HT = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(204, 0, 204));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("START");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Captura de tela 2024-12-06 173658.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 470, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 360));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 93, -1));

        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        n.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nKeyPressed(evt);
            }
        });
        jPanel2.add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 290, -1));

        try {
            Da.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Da.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DaKeyPressed(evt);
            }
        });
        jPanel2.add(Da, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, -1));

        VH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHActionPerformed(evt);
            }
        });
        VH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VHKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                VHKeyTyped(evt);
            }
        });
        jPanel2.add(VH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 180, -1));

        HT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HTKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HTKeyTyped(evt);
            }
        });
        jPanel2.add(HT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 180, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("data da admissão:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("valor da hora:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("horas trabalhadas:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jButton2.setText("imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jButton3.setText("salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Captura de tela 2024-12-06 173802.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 360));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        exibir s = new exibir(c);
        s.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void VHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VHActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String nome = n.getText();
        Adm = Da.getText();
        String VHT = VH.getText();
        String HTa = HT.getText();
        funcionario f = new funcionario();
        if (nome.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor, informe seu nome");
            jLabel2.setForeground(Color.red);
            n.setForeground(Color.red);
            n.requestFocus();
            
        } else if (Adm.isBlank() || Da.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Por favor, informe sua data de admissao");
            jLabel3.setForeground(Color.red);
            Da.setForeground(Color.red);
            Da.requestFocus();
        } else if (VHT.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor, informe o valor da hora trabalhada");
            jLabel4.setForeground(Color.red);
            VH.setForeground(Color.red);
            VH.requestFocus();
        } else if (HTa.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor, informe quantas horas trabalhou");
            jLabel5.setForeground(Color.red);
            HT.setForeground(Color.red);
            HT.requestFocus();
        }   else{
        try {    
                form.setLenient(false);
                Date Admissao = form.parse(Adm);
                f.setDataAdmissao(Admissao);
                f.setNome(nome);
                f.setValor_horas(Float.parseFloat(VHT));
                f.setHoras_trabalhadas(Float.parseFloat(HTa));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Data Inválida!");
                jLabel4.setForeground(Color.red);
                Da.setForeground(Color.red);
                Da.requestFocus();
            }
            int tempoEmpresa = f.calcularTempoempresa();
            float salario = f.calcularSalario();
            
            JOptionPane.showMessageDialog(null,"Nome: " + f.getNome()
                    + "\ndata de admissão: " + f.getDataAdmissao()
                    + "\nvalor da hora trabalhada: " + f.getValor_horas()
                    + "\nhoras trabalhadas: " + f.getHoras_trabalhadas()
                    + "\nTempo na empresa: " + tempoEmpresa
                    + "\nSalario: " + salario);

            if (c.Salvar(f)) {
                JOptionPane.showMessageDialog(null, "cadastro realizado");
                n.setText(" ");
                Da.setValue(null);
                VH.setText(" ");
                HT.setText(" ");
                n.requestFocus(); 
            } else {
                JOptionPane.showMessageDialog(null, "erro");
            }
        
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void VHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VHKeyTyped
        String caracteres = "0123456789.";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
    }
    }//GEN-LAST:event_VHKeyTyped

    private void HTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HTKeyTyped
        String caracteres = "0123456789.";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
    }
    }//GEN-LAST:event_HTKeyTyped

    private void nKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Da.requestFocus();
        }
    }//GEN-LAST:event_nKeyPressed

    private void DaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            VH.requestFocus();
        }
    }//GEN-LAST:event_DaKeyPressed

    private void VHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VHKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            HT.requestFocus();
        }
    }//GEN-LAST:event_VHKeyPressed

    private void HTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HTKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            n.requestFocus();
        }
    }//GEN-LAST:event_HTKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Da;
    private javax.swing.JFormattedTextField HT;
    private javax.swing.JFormattedTextField VH;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField n;
    // End of variables declaration//GEN-END:variables
}
